[colors]
background = "#e4e6e9FF"
text_primary = "#42474cFF"
text_muted = "#6e757cFF"
accent_primary = "#ff8f40FF"
accent_secondary = "#86b300FF"
warning = "#55b4d4FF"
error = "#e65050FF"
insert_hint = "#55b4d480"
backdrop = "#e4e6e9FF"

[colors.border]
focused = "#ff8f40FF"
unfocused = "#e4e6e9FF"
scratchpad_focused = "#55b4d4FF"
scratchpad_unfocused = "#cae0e8FF"
outer = "#f8f9faFF"

[colors.overview]
background_tint = "#f8f9fa88"
badge = "#ff8f40FF"
workspace_background = "#f8f9faFF"
